name: Website Rebuild
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: download mdbook
      run: wget -O mdbook.tar.gz https://github.com/rust-lang/mdBook/releases/download/v0.3.4/mdbook-v0.3.4-x86_64-unknown-linux-gnu.tar.gz
    - name: extract mdbook
      run: tar xzvf ./mdbook.tar.gz
    - name: build book
      run: ./mdbook build --dest-dir site/
    - name: publish book
      run: |
          aws s3 sync site/ s3://opensmtpd
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
